используя  систему .Отражение;
используя  систему .Время выполнения .CompilerServices;

[ сборка : Assemblytile ( " ")]
[ сборка : AssemblyDescription ( " ")]
[ сборка : AssemblyConfiguration ( " ")]
[ сборка : AssemblyCompany ( " ")]
[ сборка : AssemblyProduct ( " ")]
[ сборка : AssemblyCopyright ( " ")]
[ сборка: AssemblyTrademark ( " ")]
[ сборка : AssemblyCulture ( " ")]

[ сборка: AssemblyVersion ("1.0.*")]

//

//
[ сборка: AssemblyDelaySign (false)]
[ сборка : AssemblyKeyFile ( " ")]
[ сборка : AssemblyKeyName ( " ")]
